# Generated by Django 4.2.7 on 2023-12-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=3000)),
                ('comment_owner_id', models.IntegerField()),
                ('comment_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=14)),
                ('password', models.CharField(max_length=20)),
                ('balance', models.FloatField(default=0)),
                ('user_id', models.IntegerField()),
                ('ordered_products', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.ImageField(upload_to='../receipt')),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=3000)),
                ('price', models.FloatField()),
                ('discount', models.IntegerField(default=0)),
                ('product_id', models.CharField(max_length=3000)),
                ('comment_ids', models.JSONField()),
                ('review_ids', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=3000)),
                ('review_owner_id', models.IntegerField()),
                ('review_photos', models.ImageField(default=None, upload_to='../reviews')),
            ],
        ),
    ]
