# Generated by Django 4.2.7 on 2023-12-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_categories_shoppingcart_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.ImageField(upload_to='receipt'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=None, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_photos',
            field=models.ImageField(default=None, upload_to='reviews'),
        ),
    ]
