# Generated by Django 4.2.7 on 2023-12-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_categories_category_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_products',
            field=models.JSONField(default={}),
        ),
    ]
