# Generated by Django 4.2.7 on 2023-12-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_categories_category_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_products',
            field=models.JSONField(default=dict),
        ),
    ]
