# Generated by Django 4.2.7 on 2023-12-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_product_category_alter_categories_category_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id_and_quantities', models.JSONField()),
                ('user_id', models.IntegerField()),
                ('payment_son', models.BooleanField()),
                ('additional_notes', models.CharField(max_length=1500)),
                ('admin_delivery', models.CharField(max_length=4000)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=None, upload_to='products'),
        ),
    ]
