# Generated by Django 4.2.7 on 2023-12-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id_and_quantities',
        ),
        migrations.AddField(
            model_name='order',
            name='order_total_payment',
            field=models.IntegerField(default=0),
        ),
    ]
