# Generated by Django 4.2.7 on 2023-12-27 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_order_order_total_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 21, 22, 4, 397196)),
        ),
    ]
