# Generated by Django 4.2.7 on 2023-12-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_order_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(default='27/12/2023 21:27:08'),
        ),
    ]
