# Generated by Django 4.2.7 on 2023-12-27 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_order_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 21, 28, 9, 764311)),
        ),
    ]
