# Generated by Django 4.2.7 on 2024-01-10 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_order_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 13, 30, 47, 427483)),
        ),
    ]
