# Generated by Django 4.2.7 on 2024-01-10 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_order_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_delivery_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 19, 53, 17, 62550)),
        ),
    ]
